name: Trigger Workflow
on:
    push:
        branches: 
            - '/release\/v[0-9]+\.[0-9]+'

jobs: 
    trigger_workflow:
        runs-on: ubuntu-latest

        steps:
            - name: checkout the repo
            uses: actions/checkout@v3