name: Trigger Workflow
on: 
    push:
        branches:
        - 'release\/v[0-9]+\.[0-9]+'

jobs: 
    trigger_workflow:
        runs-on: ubuntu-latest
        if: contains(github.event.head_commit.message, '#NORUN') != true

        steps:
          - name: Checkout the repo
            uses: actions/checkout@v3

          - name: Set up Go
            uses: actions/setup-go@v4
            with: 
              go-version: '>=1.17.0'
          - run: go version
          
          - name: Railway deploy
            uses: bervProject/railway-deploy@main
            env: 
              RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
            with: 
              service: "animated-spoon"
          
          - name: Send custom JSON data to Slack workflow
            id: slack
            uses: slackapi/slack-github-action@v1.23.0
            with:
                payload: |
                  {
                    "text": "Github Action build result",
                    "blocks": [
                      {
                        "type": "header",
                        "text": {
                          "type": "plain_text",
                          "text": "DipSA 56 CI/CD Submission"
                        }
                      },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Name:* ${{secrets.NAME}}"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Email:* ${{secrets.EMAIL}}"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Matriculation:* ${{secrets.MATRICULATION}}"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Repository:* <${{secrets.REPO}}>"
                          }
                        ]
                      },
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "${{secrets.RAILWAY_DOMAIN}}"
                        },
                        "accessory": {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "Go",
                            "emoji": true
                          },
                          "value": "click_me_123",
                          "url": "https://animated-spoon-production.up.railway.app/",
                          "action_id": "button-action"
                        }
                      }
                    ]
                  }
            env:
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK