name: Trigger Workflow
on: 
    push:
        branches:
        - '/release\/v[0-9]+\.[0-9]+'

jobs: 
    trigger_workflow:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout the repo
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with: 
            node-version: 16
        
        - name: Install dependencies
          run: npm install
        
        - name: Run test
          run: npm test
        
        - name: Railway deploy
          uses: bervProject/railway-deploy@main
          env: 
            RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
          with: 
            service: "animated-spoon"
        
        - name: Send custom JSON data to Slack workflow
          id: slack
          uses: slackapi/slack-github-action@v1.23.0
          with: 
            payload-file-path: ".github/payload/slackcontent"
          env: 
            SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
            